Added url filtering, output of account info to stdout, and custom dmenu length
andykais/bitwarden-dmenu pull request #8
Opened 2019-01-27 01:00 UTC by AGitBoy

Added some new options:
* `--stdout`: outputs username and password to stdout, rather than to the clipboard.
* `--url`: filters accounts by url.
* `-l`: sets the dmenu option `-l` for the account and field menus.

The `--stdout` and `--url` options are mostly for scripting, and the -l option is for ajusting the prompts to the user's cosmetic preferences.

2019-01-27 01:29 UTC, andykais commented
Hi there, thanks for opening a PR! These look like handy flags for scripting. Im curious what you plan to do with `--url`, will you somehow open the dmenu while being aware of a browser's open webpage?

On a less conversational topic though, I wonder if it would make sense to make these commands more general. What do you think about instead making two separate options like so:
```bash
--bw-list-args="--url https://google.com"
--dmenu-args="--lines 1"
```

that leaves the door open for those who wish to add more customization (maybe `--folderid` for `bw`)

2019-01-27 03:25 UTC, avalonwilliams commented
That seems like a good idea, and I could implement that easily.

Also, I intend to use the `--url` for minimalist scriptable web browsers (eg. uzbl, luakit), and writing bitwarden plugins for them.

2019-01-27 04:04 UTC, AGitBoy commented
I pushed your suggested changes to the master branch on my repo, and I also added a separate argument for the password dmenu and the other dmenu prompts, as the `-l` option looks rather odd on the password prompt.

2019-01-27 04:25 UTC, andykais requested changes
Looks pretty good! I am sad to see the `dmenu -i` flag go, but in loo of the new general `dmenu-args` command, it does make the most sense.

I am requesting a few small changes, just to keep things clean for the future. Address those and I will merge!

2019-01-27 04:25 UTC, andykais commented on src/schedule-cleanup.js
> +      if(!stdout) {
this should be handled in `bin/cli.js`. Choosing the stdout flag should disable any logging console.info. That shouldnt be something you need to worry about every time console.info is called. Just handle it similar to how console.debug is set if the `--verbose` flag is used.

```javascript
console.info = args['stdout']
  ? () => {}
  : console.info
```

2019-01-27 04:25 UTC, andykais commented on README.md
> +$ bitwarden-dmemu --help
typo?

2019-01-27 04:51 UTC, andykais approved these changes

2019-01-27 04:51 UTC, merged

2019-01-27 05:00 UTC, andykais commented
published in [v1.4.0](https://www.npmjs.com/package/bitwarden-dmenu)

2019-02-10 20:40 UTC, AGitBoy commented
@andykais I made an [autofill script for qutebrowser](https://github.com/AGitBoy/qutebrowser-bitwarden-dmenu) using these changes, so I just want to say thank you for being so helpful with getting this PR merged and thank you for the wonderful job you did in writing this program.

2019-02-11 15:59 UTC, andykais commented
😄 You are very welcome! I will definitely give qutebrowser and your plugin a whirl!